export const Degrees = [
  "Associate of Arts",
  "Associate of Science",
  "Associate of Applied Science",
  "Bachelor of Arts",
  "Bachelor of Science",
  "Bachelor of Fine Arts",
  "Bachelor of Applied Science",
  "Master of Arts",
  "Master of Science",
  "Master of Business Administration",
  "Master of Fine Arts",
  "Doctor of Philosophy",
  "Juris Doctor",
  "Doctor of Medicine",
  "Doctor of Dental Surgery",
];

export const Months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
